name: Database
abbreviation: db
checker: PragmaRX\Health\Checkers\Database
notify: true
column_size: 3
targets:
#  - users:
#      type: "find_first_model"
#      models:
#        - "{{ config('auth.providers.users.model') }}"
  - "query speed":
      type: "raw_query"
      connection: "default"
      query: "select * from zalo_monitors u join zalo_monitors_point pr on pr.media_users_id = u.media_users_id order by u.created_at desc"
      maximum_time: 0.05
      error_message: "Query took %sms when it should have last at most %sms"
